// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;


public class CSVParse : MonoBehaviour 
{
	public TextAsset file;

	void Start() {
		file = Setting.gameSetting.spawnCsvFile;
		Load (file);
	}

	public class Row
	{
		public string leftLane;
		public string centerLane;
		public string rightLane;

	}

	public List<Row> rowList = new List<Row>();
	public bool isLoaded = false;

	public bool IsLoaded()
	{
		return isLoaded;
	}

	public List<Row> GetRowList()
	{
		return rowList;
	}

	public void Load(TextAsset csv)
	{
		rowList.Clear();
		string[][] grid = CsvParser2.Parse(csv.text);
		// Debug.Log ("grid.length:" + grid.Length);
		for(int i = 1 ; i < grid.Length; i++)
		{
			// Debug.Log ("row index:" + i);
			Row row = new Row();
			row.leftLane = grid[i][0];
			row.centerLane = grid[i][1];
			row.rightLane = grid[i][2];
			// Debug.Log ("row left:" + row.leftLane);
			// Debug.Log ("row center:" + row.centerLane);
			// Debug.Log ("row right:" + row.rightLane);
			rowList.Add(row);
		}
		// Debug.Log ("row length:" + rowList.Count);
		isLoaded = true;
	}

	public int NumRows()
	{
		return rowList.Count;
	}

	public Row GetAt(int i)
	{
		if(rowList.Count <= i)
			return null;
		return rowList[i];
	}


}